'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
'     o código for regenerado.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Car_Game.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Asteroide_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asteroide 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Asteroide_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asteroide 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Asteroide_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asteroide 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Aumento() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Aumento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Avião_Aliado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Avião Aliado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carro_Inimigo_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carro Inimigo 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carro_Inimigo_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carro Inimigo 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carro_Inimigo_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carro Inimigo 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Escolha() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Escolha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fundo_Carros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fundo_Carros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Game_Over_Espaço() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Game_Over_Espaço", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Game_Over_Helicopetero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Game_Over_Helicopetero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Helicopter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Helicopter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Helicoptero_Aliado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Helicoptero Aliado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Helicoptero_Menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Helicoptero Menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jogador1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jogador1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Menu() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Menu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Perder() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Perder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ponto() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ponto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property REGRAS_CARROS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REGRAS_CARROS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property REGRAS_HELI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REGRAS_HELI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property REGRAS_NAVE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REGRAS_NAVE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETA_BAIXO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETA_BAIXO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seta_cima_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seta_cima_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETA_DIREITA_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETA_DIREITA_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETA_ESQUERDA5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETA_ESQUERDA5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SPACEBAR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SPACEBAR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Tiro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Tiro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tumblr_inline_mns74aF5iR1qz4rgp540() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tumblr_inline_mns74aF5iR1qz4rgp540", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UFO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UFO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UFO_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UFO 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
